# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_SplashScreenCicle.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen3")
        SplashScreen.resize(300, 300)
        SplashScreen.setMinimumSize(QtCore.QSize(300, 300))
        SplashScreen.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QFrame(self.centralwidget)
        self.container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cicle_bg = QtWidgets.QFrame(self.container)
        self.cicle_bg.setStyleSheet("QFrame{\n"
"background-color: #282a36;\n"
"color:#f8f8f2;\n"
"border-radius:120px;\n"
"font: 9pt \"Segoe UI\";\n"
"}")
        self.cicle_bg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cicle_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cicle_bg.setObjectName("cicle_bg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cicle_bg)
        self.verticalLayout_3.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.texts = QtWidgets.QFrame(self.cicle_bg)
        self.texts.setMaximumSize(QtCore.QSize(16777215, 150))
        self.texts.setStyleSheet("background-color: none;")
        self.texts.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.texts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.texts.setObjectName("texts")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.texts)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.texts)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.texts)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.empty = QtWidgets.QFrame(self.texts)
        self.empty.setMinimumSize(QtCore.QSize(0, 80))
        self.empty.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.empty.setFrameShadow(QtWidgets.QFrame.Raised)
        self.empty.setObjectName("empty")
        self.gridLayout.addWidget(self.empty, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.texts)
        self.frame.setMinimumSize(QtCore.QSize(100, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.version = QtWidgets.QLabel(self.frame)
        self.version.setGeometry(QtCore.QRect(10, 0, 80, 20))
        self.version.setStyleSheet("QLabel{\n"
"    color:rgb(151, 159, 200);\n"
"    background-color: rgb(86, 71, 90);\n"
"    border-radius:10px;\n"
"}")
        self.version.setAlignment(QtCore.Qt.AlignCenter)
        self.version.setObjectName("version")
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.texts)
        self.verticalLayout_2.addWidget(self.cicle_bg)
        self.verticalLayout.addWidget(self.container)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen3", "Login..."))
        self.label.setText(_translate("SplashScreen3", "MissXtrela-MODERN GUI"))
        self.label_2.setText(_translate("SplashScreen3", "loading..."))
        self.version.setText(_translate("SplashScreen3", "v1.00 - Beta 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
